[options]
admin_passwd = admin123
db_host = odoo19db
db_port = 5432
db_user = odoo19
db_password = odoo19
addons_path = /opt/odoo/odoo/addons,/mnt/custom_addons
#,/mnt/custom_addons/Rightlab,/mnt/custom_addons/Rightlabdev
log_level = info
# logfile = /var/log/odoo/odoo.log
