[options]
db_host = db
db_port = 5435
db_user = odoo19
db_password = odoo19
addons_path = /opt/odoo/odoo/addons,/mnt/custom_addons
#,/mnt/custom_addons/Rightlab,/mnt/custom_addons/Rightlabdev
log_level = info
# logfile = /var/log/odoo/odoo.log
