[options]
db_host = postgres
db_port = 5435
db_user = admin
db_password = root
addons_path = /opt/odoo/odoo/addons,/mnt/custom_addons
#,/mnt/custom_addons/Rightlab,/mnt/custom_addons/Rightlabdev
log_level = info
# logfile = /var/log/odoo/odoo.log
